### ISSUE TITLE
How should we organize wallets ( device wallet vs. identity wallets)

### ISSUE THREAD

**Issue by sponnet** [locals-world/locals-app#6]
Locals has a repository of accounts ( aka identities ) - should we store them in one wallet and sync that to IPFS ?

**Comment by kingflurkel** [comment]
we have a wallet containing the device pub/priv. This is used for the device syncing (one user, multi device). The ethereum wallet is stored in localstorage object that is encrypted with generated "private key", which is a salt for AES encryption. The encrypted object is added to ipfs. The "private key/salt" is stored on ipfs TWICE: once encrypted with the users password, once with the multisig thingy.  (#4)
